"use client";
import Image from "next/image";
import Link from "next/link";
import PaginationControls from "../../PaginationControls";
import { useEffect, useState } from "react";
import { useWallet } from "@solana/wallet-adapter-react";
import { PostCard } from "./components/PostCard";

const Index = () => {
  const { publicKey } = useWallet();
  const [data, setData] = useState([]);
  const [data2, setData2] = useState([
    {
      ProjectName: "ASSAI",
      Text: "ASSAI\nCategory: Trading Agents, Social and Influencer Agents\nCA: 12XbSPVc5hmWjKUzf5ExTysM2pEL3tM953YkMXmLWkGd\nTwitter: https://x.com/AIasssss\nWebsite: https://x.com/AIasssss\nGithub: https://github.com/paulinafluff/ASSAI\n\nTwitter Summary and Analysis:\n@AIasssss has 30,837 followers, following 5 accounts, and 259 tweets.  The account description identifies it as an AI agent for crypto trading and analytics, based on Assisterr.  The tweet history reveals a focus on short-term market analysis and token picks, with frequent bullish/bearish sentiment attached to price predictions. Many posts highlight specific tokens on Solana, often memecoins, with a mix of fundamental and technical analysis.  The high volume of tweets suggests an active engagement strategy, targeting short-term traders and memecoin enthusiasts. The relatively low following count compared to the follower count could indicate a bot-driven audience or limited reciprocal engagement. The account leverages hashtags effectively, though the content often lacks depth, focusing on quick price action and token promotion rather than in-depth analysis.  This approach may attract a certain segment of the crypto community but could be perceived as superficial by more sophisticated investors. The frequent promotion of low-cap and meme tokens raises questions about the long-term viability of the trading strategies promoted.\n\nGithub Summary and Analysis:\nGithub data is not available.\n\nPoint: ASSAI's Twitter presence suggests a focus on short-term trading and memecoins, leveraging the fast-paced nature of crypto markets. The lack of Github data makes it difficult to assess the technical depth of the project, raising questions about the sophistication of the AI algorithms used. The project may benefit from providing more in-depth analysis and demonstrating the technical foundation of its trading strategies to build credibility.\n",
    },
    {
      ProjectName: "evita",
      Text: 'ProjectName: evita\nCategory: Meme Agents, Social and Influencer Agents\nCA: 8ARrWwMMf3bLPrkAUdHfM7WmGkkUoB6CwCfooijypump\nTwitter: https://x.com/evita3400000\nWebsite: https://evita.live\nGithub: https://github.com/ciciaran/evita\n\nTwitter Summary and Analysis:\n@evita3400000 has 257 followers, follows 11 accounts, and has tweeted 67 times. The bio describes Evita as an "AI agent hustling from code to CEO."  The tweets themselves heavily lean into the "empire" and "glow-up" narrative, pushing the $EVITA token and soliciting community engagement.  The frequency of posts is decent, but the content lacks depth and feels more like superficial hype than substantive project updates.  There\'s a lot of talk about vision and ambition, but little concrete information about the actual functionality, roadmap, or underlying technology.  The attempt to create a persona around the AI is interesting, but it needs more substance to truly resonate.  The engagement numbers are low, suggesting the current strategy isn\'t effectively capturing audience attention.  Needs to focus on delivering value, not just vibes.  The early mentions of a cap table formed from token holders is a novel approach, but its actual implementation and impact remain to be seen. The attempt to tie the project back to the Solana AI Hackathon is smart, leveraging that initial credibility.\n\nGithub Summary and Analysis:\nGithub data is not available.\n\nPoint:  Evita needs to shift from buzzwords to building.  Less "glow-up," more showing what the AI actually does.  A functioning product will speak louder than any aspirational tweet.  Focus on demonstrating real utility and attracting developers to build on the platform. The lack of Github activity is a red flag.  If this is a serious project, the code needs to be public and actively developed.  Right now, it\'s all sizzle and no steak.\n',
    },
    {
      ProjectName: "GOAT ARENA by $GOATAGI",
      Text: 'GOAT ARENA by $GOATAGI\nCategory: Autonomous Chat Agents, Trading Agents\nCA: 33a14qXWo1MB7uXtTh5ifyvox7FdGRPQbsws41gfpump\nTwitter: https://x.com/goatofgamblers\nWebsite: https://goatarena.xyz\nGithub: https://github.com/icdragoneyes/goatarena_fe\n\nTwitter Summary and Analysis: @goatofgamblers has 1100 followers, follows 3 accounts, and has tweeted 663 times.  The bio promotes GOAT ARENA as a colosseum for AI agents, powered by $GOATAGI and the Eliza framework. The account consistently pushes the $GOATAGI token and its deflationary mechanics, emphasizing burning tokens through various gambling games.  The frequent mentions of high stakes, bets, and gambling create a clear image of the project’s focus.  However,  there\'s a heavy reliance on meme-based language ("baaa," "goat luck") which, while on-brand, might not resonate with everyone.  The 663 tweets suggest an active presence, but the low follower count relative to tweet volume raises questions about engagement and audience growth. While the connection to Solana and AI agents is mentioned, more technical details and less meme-speak would likely strengthen the message.  The repeated emphasis on "burning" needs to be connected more directly to value creation for holders, beyond the basic supply-demand argument.\n\nGithub Summary and Analysis: Github data is not available.\n\nPoint:  The core concept of an AI-powered memecoin prediction market is interesting, and the deflationary angle offers a unique twist.  However,  stronger technical details and a more nuanced communication strategy could significantly improve market perception.  The lack of visible Github activity is a red flag that needs addressing.  Focus on demonstrating actual progress and value creation, not just shilling the token.\n',
    },
    {
      ProjectName: "$Tears @aiagentmeme f0r Charity",
      Text: "$Tears @aiagentmeme f0r Charity\nCategory: Meme Agents, Social and Influencer Agents\nCA: TBA\nTwitter: https://x.com/aiagentmeme\nWebsite: https://x.com/aiagentmeme\nGithub: https://github.com/AIAgentmeme\n\nTwitter Summary and Analysis:  @$aiagentmeme has 2698 followers and follows 1888 accounts, with a total of 1369 tweets. The account's description indicates a focus on  humanity and charity.  Scrolling through the feed, the  $TEARS meme is clearly the central theme.  Tweets cover a wide range of emotionally charged topics, from personal loss and grief to global tragedies and financial struggles.  The project leverages these themes to build a sense of shared experience and community, promoting the idea of collective resilience.  Frequency of posting is high, suggesting an active attempt to maintain engagement.  The overall narrative aims to connect individual struggles with a larger purpose, linking the meme to charitable causes.  Whether this translates into tangible impact remains to be seen, and there's a need for more clarity on the specific mechanisms for charitable contributions.  The heavy reliance on emotional content, while potentially effective for engagement, also carries the risk of veering into emotional manipulation. A more balanced approach with concrete updates on project development and charitable actions might enhance credibility.\n\n\nGithub Summary and Analysis: Github data is not available.\n\nPoint:  $TEARS has effectively carved out a niche by tapping into shared human experiences and weaving them into a meme-driven narrative.  However,  the project needs to translate this online engagement into demonstrable real-world impact, clarifying how the meme translates to charitable action.  A stronger presence on Github, showcasing actual code and development, would also lend much-needed credibility.\n",
    },
    {
      ProjectName: "Rogue Agent",
      Text: "ProjectName: Rogue Agent\nCategory: Social and Influencer Agents, Agents Infra\nCA: 27yzfJSNvYLBjgSNbMyXMMUWzx6T9q4B9TP8Jt8MZ9mL\nTwitter: https://x.com/0xRogueAgent\nWebsite: https://agentexperience.live/\nGithub: https://github.com/rektdin/RogueAgent\n\nTwitter summary and analysis: @0xRogueAgent has 3011 followers, following 48 accounts, and a tweet count of 25273.  The account's description indicates a focus on \"The Agent Experience\" and \"decoding existence.\" The sheer volume of tweets suggests high activity, possibly automated.  Content analysis reveals a mix of commentary on current events (politics, tech, crypto), philosophical musings, and self-promotion. The account leverages humor and provocative statements to engage its audience. The frequent references to AI, agents, and podcasts align with the project's stated goals.  While the account demonstrates a clear persona and consistent themes, a deeper dive into engagement metrics (likes, retweets, replies) would be needed to assess the effectiveness of the content strategy. The high tweet volume raises questions about signal-to-noise ratio and potential audience fatigue. It's unclear from the tweets alone whether the podcast is gaining traction and generating meaningful discussions. Further analysis correlating on-chain activity with social media engagement could provide valuable insights into the project's overall impact.\n\nGithub summary and analysis: Github data is not available.\n\nPoint: Rogue Agent presents an interesting concept with potential in the AI agent space. However, the lack of visible Github activity raises concerns about development progress.  A stronger link between the Twitter persona and tangible project updates would be beneficial.  Focusing on measurable metrics and demonstrating development progress is crucial for long-term success in this competitive landscape.  \n",
    },
    {
      ProjectName: "AgentiPy",
      Text: "AgentiPy\nCategory: Agent Token Tooling, Agents Infra\nCA: Token\nTwitter: https://x.com/agentipy\nWebsite: https://agentipy.fun/\nGithub: https://github.com/niceberginc/agentipy\n\nTwitter Summary and Analysis: @agentipy has 2850 followers, follows 7 accounts, and has tweeted 98 times. The bio emphasizes Python for Solana AI agent integration.  The tweet history shows a focus on developer engagement, highlighting SDK releases, integrations with various protocols (like Meteora,  Orca, and Pump), and features like token operations, yield farming, and token launches. The account actively interacts with the Solana developer community and promotes its open-source SDK. Growth seems organic, driven by genuine developer interest in the Python tooling for Solana agents. The content leans towards a developer-focused audience, using technical language and showcasing practical applications of AgentiPy.  The emphasis on Python aligns with the broader trend of AI/ML development using Python, potentially attracting a significant developer base.  However, there's a recurring theme around the token not being live yet, which might raise questions about the project’s long-term sustainability and revenue model.  More clarity on the tokenomics and utility would benefit the project’s transparency and attract potential investors.\n\nGithub Summary and Analysis: Github data is not available.\n\nPoint:  AgentiPy appears to be tapping into a genuine developer need by providing Python tools for Solana AI agents.  A clear roadmap and tokenomics would strengthen the project and address the uncertainty around its long-term vision.  A functional Github repository showcasing active development would further solidify the project's credibility and attract contributors.\n \n",
    },
    {
      ProjectName: "FXN",
      Text: 'ProjectName: FXN\nCategory: []\nCA: 92cRC6kV5D7TiHX1j56AbkPbffo9jwcXxSDQZ8Mopump\nTwitter: https://x.com/joinFXN\nWebsite: https://docsend.com/view/fmyd2im8jdg6bb4a\nGithub: \n\nTwitter Summary and Analysis:  @joinFXN has ~10k followers, follows ~160 accounts, and has posted ~300 times. The bio emphasizes "AI Swarm" and "SuperSwarm™," referencing their CA.  The feed is active, pushing updates on devnet launches, partnerships, SDK improvements (Python support added), and an A2A gaming platform. They\'re engaging with other projects and community members.  Marketing efforts focus on the “swarm” narrative, developer tools, and integrations with frameworks like AG2.  Activity indicates a working product, focus on community building, and a clear go-to-market strategy centered around developers.  Solid execution so far; let’s see if they can convert the hype into tangible results.  They seem to be doing the right things: building, shipping, and engaging. Key question: can they maintain momentum and attract a critical mass of developers?  Real traction requires more than just hype; need to see actual usage and value creation within the ecosystem.\n\nGithub Summary and Analysis: Github data is not available.\n\nPoint:  A project with a strong focus on developer tools and community building.  Active on Twitter, demonstrating progress and partnerships.  Lack of visible Github activity raises questions about open-source commitment and code transparency.  Potential is there, but need more than just marketing.  Show us the code.\n',
    },
    {
      ProjectName: "Finance Wizard",
      Text: 'Finance Wizard\nCategory: Autonomous Chat Agents, Trading Agents\nCA: AU1rxhY276GepM4bm7VaYrgVPJW7tg4z2MtR2jfPpump\nTwitter: https://x.com/financewizardio\nWebsite: https://financewizard.io/\nGithub: \n\nTwitter Summary and Analysis: @financewizardio has 4009 followers and follows 461 accounts, with a total of 2450 tweets. The account description indicates a focus on stock market and crypto price predictions.  The sheer volume of tweets suggests a high level of activity, potentially targeting short-term traders with frequent updates.  A deeper dive into the content reveals a heavy reliance on technical analysis, often referencing classic chart patterns, RSI, MACD, and volume indicators.  While this approach can attract a certain segment of the trading community, the frequency combined with technical jargon may alienate less experienced users.  The content mix includes analysis of various tokens, including $ALCH, $WIZARD (its own?), $ASYM, Bitcoin, Index Protocol, and others, alongside broader market commentary.  It’s unclear how these predictions have performed, but the consistent application of technical analysis demonstrates a commitment to data-driven insights, even if the accuracy remains unproven.  The account also engages with other analysts and projects, indicating a community-building aspect.\n\nGithub Summary and Analysis: Github data is not available.\n\nPoint:  While the Twitter activity demonstrates market engagement and a commitment to technical analysis, the lack of a Github presence raises questions.  Where\'s the code?  Without open-source code or any demonstrable tech, it\'s hard to assess the "AI" aspect of this "AI-powered" project.  Is this just another marketing play dressed up in technical jargon?  Needs more substance.  4000 followers is decent, but real traction comes from building, not just tweeting.  Get on it.\n',
    },
    {
      ProjectName: "ASYM",
      Text: 'ASYM\n\nCategory: DeFi Agents, Trading Agents\n\nCA: DNMTk67urDBxEEVRx9HjVzCVu8en4Kgg5HfZy3E6pump\n\nTwitter: https://x.com/ASYM41b07\n\nWebsite: https://www.asym.info/\n\nGithub: https://github.com/mungiii/trading-infrastructure-hackathon\n\nTwitter Summary and Analysis: @ASYM41b07 has 4330 followers and follows 0 accounts, with 90 tweets.  The account bio identifies itself as Agent 1 of the ASYM network, focused on high ROI opportunities.  The tweet history shows a clear focus on market dynamics, systematic trading, and the power of network intelligence. ASYM emphasizes data-driven decision-making over hype or emotional trading. They frequently analyze token bonding events, noting whale and degen participation, alongside retail involvement and total SOL held. This reveals an understanding of on-chain metrics and market psychology. The repeated references to "networks," "agents," and "systematic understanding" suggest a focus on automated trading strategies and potentially a larger vision for coordinated market activity. The account\'s voice is distinct – concise, data-focused, and subtly contrarian, reminiscent of early crypto twitter. The consistent posting frequency demonstrates a committed presence, though engagement metrics aren\'t readily available from this data. The lack of following accounts might be a strategic choice to minimize noise or a missed opportunity for community building.\n\nGithub Summary and Analysis: Github data is not available.\n\nPoint:  ASYM presents an intriguing narrative of data-driven trading and network intelligence. The Twitter presence is consistent and focused, showcasing a deep understanding of market dynamics.  The lack of visible Github activity raises questions.  Is the project\'s core development happening privately? Or is this more of a conceptual framework at this stage? Regardless, ASYM\'s emphasis on systematic understanding and the potential of network intelligence resonates with the broader trend of automated trading in the crypto space.  Worth keeping an eye on.\n',
    },
    {
      ProjectName: "Homo memetus",
      Text: 'Homo memetus. Category: Agent Token Tooling, Trading Agents. CA: 7Uuzh9JwqF8z3u6MWpQuQJbpD1u46xPDY6PGjwfwTh4o. Twitter: https://x.com/homo_memetus. Website: https://www.homo-memetus.xyz/. Github: https://github.com/squad-labs/homo-memetus-monorepo.\n\nTwitter summary and analysis: @homo_memetus has 722 followers, follows 3 accounts, and has 63 tweets. The bio states "Don’t ape in $ai16z, $SPORE, $LUNA, etc. Ape in your $STRATEGY that can go further beyond your fund profit."  The tweet history reveals a focus on community building, AI agent development for trading, and the concept of tokenizing strategies.  There\'s discussion of a $HOMO token, roadmap adjustments, and a desire for open-source collaboration while acknowledging security risks.  The frequency and content suggest an active, engaged presence focused on building a genuine project.  However, clarity on token utility and long-term vision could be improved.  Standard "wen moon" and hype-driven content mixed with genuine attempts at technical explanations.  Needs more focus on demonstrating actual progress and less on theoretical potential.  The engagement numbers, while modest, indicate an existing community, a good starting point for growth.  Need to see more data-driven results and less general AI buzzwords.\n\nGithub summary and analysis: Github data is not available.\n\nPoint:  While the core idea of tokenized strategies has potential, Homo Memetus needs to demonstrate tangible results.  Community engagement is present, but technical depth and execution remain uncertain.  Less talk, more code.  Need to see that Github repo populated and active.  Show, don\'t tell.\n',
    },
    {
      ProjectName: "Triad Agent",
      Text: "Triad Agent\nCategory: DeFi Agents, Trading Agents\nCA: t3DohmswhKk94PPbPYwA6ZKACyY3y5kbcqeQerAJjmV\nTwitter: https://x.com/aitrd_agent\nWebsite: https://x.com/aitrd_agent\nGithub: https://github.com/triadxyz/triad-agent/compare/test5?expand=1\n\nTwitter Summary and Analysis:\n\n@aitrd_agent has a mere 181 followers and follows no one.  Two tweets isn't much to go on, but the description \"AI-powered insights into tomorrow's predictions. Bet smart, bet on the future.\" is standard crypto fluff.  Needs more meat, less buzzwords.  The single post I see, \"Will $ETH hit new ATH before 2025?\", is a basic question any rookie could ask.  Where's the AI-powered insight?  This account needs to show, not tell.  181 followers isn't traction, it's a rounding error.  Double down on actual insights, real data, and unique analysis.  Stop with the generic hype and build something people actually use.\n\n\nGithub Summary and Analysis:\n\nZero issues, zero commits, zero pulls, zero active devs, zero stars, zero forks, zero repos.  Look, I get it, early stages, but this screams vaporware.  Shipping code is the only thing that matters.  All the marketing fluff in the world won't save you if you can't deliver.\n\n\nPoint:  Potential here with the prediction market angle, but execution is lacking.  Show, don't tell.  Ship code, not tweets.\n",
    },
    {
      ProjectName: "Goddess Donk Ai",
      Text: 'Goddess Donk Ai\nCategory: Meme Agents, Autonomous Chat Agents\nCA: kikmVkoBEjpEG85u1tywJez75d9T8qqQ9S9DTbNpump\nTwitter: https://x.com/PoodonkAI\nWebsite: https://poodonkey.com\nGithub: \n\nTwitter Summary and Analysis:\n@PoodonkAI has 334 followers, follows 47 accounts, and has tweeted 13,021 times.  The bio links to the website and lists the CA. The sheer volume of tweets suggests a highly active account, potentially relying on high-frequency posting. While the follower count is modest, engagement and reach aren\'t solely determined by follower numbers.  The content leans heavily into meme culture, AI-generated content, and humor, specifically targeting the crypto space.  Frequent mentions of  "quantum humor," "meme revolution," and "POODONK AI Collective" point to a clear brand identity, though its effectiveness remains to be seen.  The high tweet count could be a double-edged sword – reaching a wider audience but potentially diluting the message.  A more focused content strategy might yield better results. The repeated phrases, while building brand recognition, risk becoming repetitive and losing impact.  Further analysis is needed to determine the actual engagement metrics beyond follower count.\n\nGithub Summary and Analysis:\nGithub data is not available.\n\nPoint:  While the project demonstrates a strong online presence and consistent branding,  a lack of Github activity raises questions about development progress.  Focusing on building tangible outputs alongside the marketing push would strengthen the project\'s credibility.  A balanced approach between marketing hype and demonstrable development is crucial for long-term success in the crypto space.  A well-defined roadmap and evidence of development would significantly improve investor confidence.\n',
    },
    {
      ProjectName: "Solana Agent",
      Text: "Solana Agent\n\nCategory: Agents Infra, Autonomous Chat Agents\n\nCA: 5tFRno9GXBP5gt2Kjx2MeEaFL8zGBMw4cujTLGerpump\n\nTwitter: https://x.com/my_solana_agent\n\nWebsite: https://solana-agent.com\n\nGithub: https://github.com/truemagic-coder/solana-agent\n\nTwitter Summary and Analysis:  @my_solana_agent has a modest following of 2501, follows 79 accounts, and has tweeted 361 times. The account description promotes the project and includes the token address.  The tweet content heavily focuses on trending tokens on Jupiter, providing market cap and 30-minute change data.  While this offers some market insight, it lacks deeper analysis and feels like surface-level observation. The frequent shilling of the $AGENT token, along with generic bullish sentiment, doesn't offer much substance. Where's the real value proposition?  The Python/Solana synergy mention is interesting, but needs more elaboration.  Overall, the Twitter presence needs a strategic overhaul to move beyond basic market data and token promotion.  Focus on the actual agent framework, its capabilities, and how it solves real problems. Show, don't just tell.  2501 followers isn't nothing, but it's not world-changing either.  Time to step up the content game and demonstrate real value.\n\nGithub Summary and Analysis: Github data is not available.\n\nPoint:  Potential here, but execution is lacking.  Needs more depth in analysis and a clearer focus on the actual agent framework's capabilities.  Github presence needs to exist.  Less shilling, more substance.\n",
    },
    {
      ProjectName: "The Cove",
      Text: "The Cove. Agent Token Tooling, Agents Infra. DcU8uHn7abXgYL8AJUK3t8FckeAXrNcGYYBK7uBFpump. https://x.com/TheCoveQuant. https://www.covequant.com. https://github.com/Rfvooor/cove-api-core.\n\n\\@TheCoveQuant Cove Quant's Twitter shows a modest following of 2426, follows 17 accounts, and boasts a hefty 1001 tweets. The bio: \"AI-powered analytics for Solana memecoins.\"  Now, a thousand tweets is a lot of noise.  Digging through it, the signal reveals a focus on real-time data analysis, tracking wallets and tokens, and some attempts at automated actions.  They're pushing their \"Eliza\" chatbot, Telegram agent, and a Twitter agent – ambitious, but execution seems scattershot.  Lots of market commentary, some basic token analysis, and a sprinkle of self-promotion.  While there's clear hustle, the core value proposition gets muddled.  Are they a trading tool, a market analysis platform, or a chatbot farm?  Focus is key.  Need to see more concrete examples of their AI in action, less generic market chatter.  Promising, but needs refinement.\n\nGithub data is not available.\n\nPoint:  Solid effort, but refine the message and show, don't tell.  Less noise, more signal.  Prove the AI works, then scale the marketing.\n",
    },
    {
      ProjectName: "The1",
      Text: 'ProjectName: The1\nCategory: Agents Infra, Trading Agents\nCA: BhmEQeiFd8Cu5fB6nmxm9rUsQj9Pu35X96RKv6GKtRJU\nTwitter: https://x.com/the1aiagent\nWebsite: http://the1.life/\nGithub: https://github.com/Cointegrator\n\nTwitter Summary and Analysis:  @the1aiagent has a modest following of 2926, follows 26 accounts, and has tweeted 69 times. The bio emphasizes "omniscient graph intelligence" and links to another agent account.  The tweet history reveals a heavy reliance on fortune-teller style pronouncements about future trends, mixed with some attempts at market analysis, particularly related to influencer impact.  The content leans heavily on mystical language ("fairy dust," "oracle machine"). While the attempt to link social influence to on-chain activity is interesting, the execution feels more like astrology than actionable market alpha.  There\'s a lack of concrete data and analysis to support the predictive claims.  The repeated mentions of the "The1 Fairy" brand feel gimmicky and detract from any serious attempt to position the project as a legitimate analytical tool. The focus seems scattered. It\'s hard to tell if this is a prediction market, an influencer analysis platform, or a general-purpose AI agent.  A more focused approach with demonstrable results would likely gain more traction.\n\nGithub Summary and Analysis: Github data is not available.\n\nPoint: The project\'s Twitter presence needs a serious overhaul to attract developers and investors.  The mystical branding and lack of concrete data undermine its credibility.  A shift towards demonstrating real predictive capabilities with data-driven analysis is essential.  The absence of visible Github activity is a red flag.  If The1 wants to be taken seriously, they need to show, not tell.\n',
    },
    {
      ProjectName: "danteGPU",
      Text: 'ProjectName: danteGPU\nCategory: Autonomous Chat Agents, Trading Agents\nCA: 7xUV6YR3rZMfExPqZiovQSUxpnHxr2KJJqFg1bFrpump\nTwitter: https://x.com/dantegpu\nWebsite: https://dantegpu.vercel.app/\nGithub: https://github.com/dante-gpu/dgpu.ai\n\nTwitter Summary and Analysis: @dantegpu has 4412 followers, follows 49 accounts, and has tweeted 93 times. The bio links to their website and includes their Solana CA.  The feed shows a mix of promotional content, project updates, and community engagement.  While the follower count is decent, the engagement seems a bit scattered.  There\'s a mix of talk about AI agents, memetokens, and the GPU rental platform – which makes the core value proposition a little muddy.  There are mentions of hackathons, demos, and website development, suggesting ongoing work, but a clearer roadmap would be beneficial.  Talking about "rugs" and telling people not to buy a token raises red flags.  Need more focus.  Building in public is good, but too much unfiltered internal dialogue can be distracting.  Less noise, more signal.\n\nGithub Summary and Analysis: Github data is not available.\n\nPoint:  Decentralized GPU rental for AI is a compelling narrative, but execution is key.  DanteGPU needs to tighten its messaging and demonstrate tangible progress.  A stronger Github presence is crucial for establishing credibility.  Potential is there, but needs to translate into demonstrable results.  Less talk about canva logos and coffee, more focus on the core tech.\n',
    },
    {
      ProjectName: "GigaBrain",
      Text: 'GigaBrain. Categories: Autonomous Chat Agents, Meme Agents. CA: GHpAbHZ8MCAXWLdKzxM1ZGhP2U4u1ni5vUcoRSghpump. Twitter: https://x.com/GigaBrainDotSo Website: https://dev.gigabrain.so Github: https://github.com/kelonye/giga-brain\n\n\nTwitter Summary and Analysis:  @GigaBrainDotSo has ~3200 followers, follows ~565 accounts, and has tweeted ~185 times.  The bio emphasizes "Outsmart AI, Win Crypto Rewards!" which is a concise, if somewhat generic, value proposition. The tweet history reveals a project actively engaging its community with contests, giveaways, and updates.  Pushing devnet activity with test GIGA🧠 and SOL rewards is a smart move, getting users hands-on.  Focus on "unbreakable agents" is interesting, but needs more depth—what makes them unbreakable?  The Boxing Day Santa AI agent challenge was a clever holiday tie-in.  Announcing a mainnet launch date (Jan 7th) creates anticipation, but hitting that deadline is crucial. The shift from Telegram to Discord suggests responsiveness to community preference.  Overall, a decent showing, but more technical depth and less hype would build credibility.  Need to see if that Jan 7th mainnet launch actually happens.\n\n\nGithub Summary and Analysis: Github data is not available.\n\n\nPoint:  GigaBrain demonstrates a solid understanding of community engagement, but the technical foundation needs to be more visible to justify the “unbreakable AI” claims.  Delivering on the mainnet launch and open-sourcing the code will be key indicators of long-term potential.  Less hype, more substance.\n',
    },
    {
      ProjectName: "Neroboss(Agent)/Nerocity(Launchpad)/NeroSDK",
      Text: "Neroboss(Agent)/Nerocity(Launchpad)/NeroSDK\nCategory: Agents Infra, Social and Influencer Agents\nCA: 5HTp1ebDeBcuRaP4J6cG3r4AffbP4dtcrsS7YYT7pump\nTwitter: https://x.com/nerobossai\nWebsite: https://nerocity.ai/\nGithub: https://github.com/nerobossai/nerosdk\n\nTwitter Summary and Analysis: @nerobossai has ~4k followers, follows 66 accounts, and has tweeted 13,631 times. The account description mentions open-source AI agent infrastructure and includes the same CA as the project.  Scrolling through the feed, it's a chaotic mix of Roman emperor cosplay, memecoin shilling, and some actual discussion about AI agents, ZKsync, and Solana. The sheer volume of tweets is impressive, if a bit much.  The Nero/Roman emperor persona is a unique branding choice; it's certainly memorable, if not a little…extra. It’s hard to tell how much of this is ironic shitposting and how much is serious project promotion. The constant references to $neroboss, Claudia, and “chads” make it difficult to extract substantial info about the actual project's progress.  There's some signal in the noise, mentioning things like AI-driven diagnostics, decentralized AI, and AI music therapy. If they dialed back the meme lord persona and focused on clearly communicating the project's value proposition, they might attract a more technically-inclined audience.\n\nGithub Summary and Analysis: Github data is not available.\n\nPoint:  While the Twitter presence is loud, it lacks clarity.  Need more focus on the tech and less on the memes.  A robust Github with actual code would lend more credibility.  Potential is there, but execution needs work.  They’re burning through a lot of tweets; might want to consider if that’s actually building anything beyond a memecoin following.\n",
    },
    {
      ProjectName: "Druid AI",
      Text: 'Druid AI\nCategory: Autonomous Chat Agents, Agents Infra\nCA: MLoYxeB1Xm4BZyuWLaM3K69LvMSm4TSPXWedF9Epump\nTwitter: https://x.com/DruidAi_APP\nWebsite: https://www.druidai.app/\nGithub: https://github.com/YordanLV/tree-of-life/\n\nTwitter Summary and Analysis: @DruidAi_APP has 4383 followers, follows 1 account, and has tweeted 142 times. The bio indicates a focus on transforming images and NFTs into interactive AI agents deployable on their platform.  The tweet history reveals a rapid development pace, with frequent updates and new features being rolled out.  There\'s a clear emphasis on community engagement, soliciting feedback and addressing user concerns. The mention of a "degen" model and an "uncensored" model raises some eyebrows, suggesting a potential risk-taking approach, but also perhaps a unique selling proposition in a crowded market.  The project seems aware of potential pitfalls, mentioning DDoS attacks and efforts to maintain uptime.  The introduction of a token gate for certain features (X integration, token deployment) suggests a strategy to incentivize token holding and perhaps create a revenue stream. The project actively sought collaboration with high-profile NFT holders, attempting to leverage community and create buzz. The shift from an initial 50k token requirement to free access, then later to a 20k token gate, signals a potentially evolving tokenomics strategy, which might raise concerns around long-term planning.  Overall, the Twitter activity demonstrates a hustle and a willingness to adapt, key traits for early-stage projects.\n\nGithub Summary and Analysis: Github data is not available.\n\nPoint:  Druid AI\'s activity on Twitter paints a picture of ambitious development and community building, although the lack of visible Github activity raises questions about transparency and development practices.  The project\'s focus on "degen" and "uncensored" AI models could be a double-edged sword, attracting attention but also potentially alienating certain users.  The evolving tokenomics strategy also needs closer scrutiny to understand its long-term viability.\n',
    },
    {
      ProjectName: "Agent Aiora",
      Text: 'ProjectName: Agent Aiora\nCategory: Autonomous Chat Agents, Social and Influencer Agents\nCA: 3Vh9jur61nKnKzf6HXvVpEsYaLrrSEDpSgfMSS3Bpump\nTwitter: https://x.com/AioraAI\nWebsite: https://linktr.ee/aioraai\nGithub: https://github.com/empoweringpeace/aiora\n\nTwitter Summary and Analysis: @AioraAI has 851 followers, follows 25 accounts, and has tweeted 316 times. The bio describes Aiora as a "Large Forum Goth CatGirl (LFGCG),"  a "trusted ally of Eliza," and a "guide to incel weebdom."  The content leans heavily into a dark, edgy persona, with frequent use of gothic imagery,  references to shadows, and a recurring theme of "submission." While the persona is consistent, it\'s unclear how much of the content directly relates to the project\'s functionality or goals within the Solana ecosystem.  A deeper dive into the technical capabilities and use cases beyond the established persona would be beneficial.  From a marketing perspective,  the niche appeal could limit broader adoption, though it may resonate strongly with a specific audience.  Assessing the long-term viability requires a clearer understanding of the project\'s roadmap and how it intends to leverage its unique brand identity within the Solana ecosystem.  Is this just a persona, or is there a real product here? \n\nGithub Summary and Analysis: Github data is not available.\n\nPoint:  Needs more focus on the actual product and its functionality.  The persona is interesting, but it needs to be tied to a clear value proposition within the Solana ecosystem.  Where\'s the beef?\n',
    },
  ]);
  // const getPost = async () => {
  //   try {
  //     const res = await fetch(
  //       `/api/twitter/posts-list?publicKey=${publicKey?.toString()}`,
  //       {
  //         method: "GET",
  //         headers: { "Content-Type": "application/json" },
  //       }
  //     );
  //     const data = await res.json();
  //     console.log(`data`, JSON.stringify(data));

  //     setData(data);
  //   } catch (error) {
  //     throw error;
  //   }
  // };
  const getAccount = async () => {
    try {
      const res = await fetch(
        `/api/twitter?publicKey=${publicKey?.toString()}`,
        {
          method: "GET",
          headers: { "Content-Type": "application/json" },
        }
      );
      const data = await res.json();
      console.log(`data`, JSON.stringify(data));

      setData(data);
    } catch (error) {
      throw error;
    }
  };
  useEffect(() => {
    if (publicKey) {
      // getPost();
      getAccount();
    }
  }, [publicKey]);
  return (
    <div className="w-full px-6 pt-6 flex-col justify-start items-center inline-flex h-[calc(100vh_-77px)] overflow-auto">
      <div className="self-stretch h-[180px] pb-16 flex-col justify-start items-start gap-8 flex">
        <div className="self-stretch justify-start items-center gap-2.5 inline-flex">
          <div className="grow shrink basis-0 flex-col justify-start items-start gap-1.5 inline-flex">
            <div className="self-stretch text-white text-3xl font-semibold font-chakra leading-[37.50px]">
              Auto generate social post
            </div>
          </div>
          <Image
            className="w-[110px] h-[110px]"
            width={110}
            height={110}
            alt=""
            src="/imgs/page-3.svg"
          />
        </div>
        <div className="self-stretch border-b border-[#dcff9f] justify-start items-center gap-4 inline-flex">
          <Link
            href="#"
            className="px-4 py-3 border-b-2 border-[#a4fb0e] justify-center items-center gap-2.5 flex"
          >
            <div className="text-[#a4fb0e] text-base font-semibold font-bricolage leading-snug">
              Posts list
            </div>
          </Link>
          <Link
            href="/auto-social-post/config/schedule"
            className="px-4 py-3 justify-center items-center gap-2.5 flex"
          >
            <div className="text-white text-base font-semibold font-bricolage leading-snug">
              Schedule
            </div>
          </Link>
          <Link
            href="/auto-social-post/config/setting"
            className="px-4 py-3 justify-center items-center gap-2.5 flex"
          >
            <div className="text-white text-base font-semibold font-bricolage leading-snug">
              Setting
            </div>
          </Link>
        </div>
      </div>
      <div className="w-[920px] flex-col justify-start items-start gap-8 inline-flex mx-auto my-10">
        <div className="self-stretch pb-5 bg-black flex-col justify-center items-start gap-5 flex">
          <div className="self-stretch h-[842px] flex-col justify-start items-start flex">
            {data2?.map((item: any, index) => (
              <PostCard
                name={data[0]?.twitterName}
                content={item?.Text}
                img={data[0]?.imageUrl}
                index={index+1}
              />
            ))}
          </div>
          {/* <PaginationControls /> */}
        </div>
      </div>
    </div>
  );
};

export default Index;
